services:
  postgresql:
    image: 'postgres:latest'
    ports:
      - '5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'mydb'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
